version: "1.1.1"

services:
  api:
    build: ./
    environment:
      - NODE_ENV=development
      - ENABLED_DOCKER=true
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - db
  db:
    image: mongo:5.0.19-focal
    attach: false
    ports:
      - 27017:27017
    volumes:
      - sco-kubide-backend:/data/db

volumes:
  sco-kubide-backend: